name: Cloud Native CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:

        - name: Checkout code
          uses: actions/checkout@v5

        - name: Set up Python
          uses: actions/setup-python@v6
          with:
            python-version: "3.12"
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Run Tests
          run: pytest
        - name: Check Docker Hub Username
          run: |
            echo "Username length: ${#DOCKERHUB_USERNAME}"
            printf '%s' "$DOCKERHUB_USERNAME" | od -An -t x1
          env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        - name: Build Docker Image
          run: docker build -t cloud-native-cicd:local .  
        - name: Tag docker image
          run: docker tag cloud-native-cicd:local ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-cicd:local
        - name: Push to Docker Hub
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-native-cicd:local